#!/usr/bin/env bash
#
# Terraform equivalent of 03_lakeflow_connect_demo.sh.
# Creates Lakeflow Connect resources (schemas, connection, gateway pipeline,
# ingestion pipeline, trigger job, permissions) via Terraform.
#
# Option: use Databricks provider from rsleedbx fork (num_workers_0 branch):
#   export USE_NUM_WORKERS_0_PROVIDER=1
#   source 03_lakeflow_connect_demo_tf.sh
#
# Prerequisites: same as 03_lakeflow_connect_demo.sh (source 00, 01_* , 02_* first).
set -u

if [[ "$0" == "$BASH_SOURCE" ]]; then
  echo "Script is being executed directly. Please run as: source $0"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/deploy/tf"
TFVARS_FILE="${TF_DIR}/terraform.tfvars"
NUM_WORKERS_0_PROVIDER_REPO="https://github.com/rsleedbx/terraform-provider-databricks"
NUM_WORKERS_0_PROVIDER_BRANCH="num_workers_0"
PLUGIN_DIR="${TF_DIR}/.provider-cache"

# Ensure connection_spec_create exists (used by demo flow: get_secrets + connection_spec_from_env)
if ! declare -f connection_spec_create &>/dev/null; then
  connection_spec_create() {
    get_secrets "${DB_HOST}" && connection_spec_from_env STATE
  }
  export -f connection_spec_create
fi

# Load same env and names as 03_lakeflow_connect_demo.sh
export STOP_AFTER_SLEEP="${STOP_AFTER_SLEEP:-20m}"
NINE_CHAR_ID=$(date +%s | xargs printf "%08x\n")
export NINE_CHAR_ID

DB_EXIT_ON_ERROR="PRINT_EXIT" DBX auth env
DATABRICKS_HOST_NAME=$(jq -r .env.DATABRICKS_HOST /tmp/dbx_stdout.$$)

if [[ -z "${CONNECTION_NAME:-}" ]]; then
  CONNECTION_NAME=$(echo "${WHOAMI}_${DB_HOST}_${DB_CATALOG}_${USER_USERNAME}" | tr ' .@' '_')
fi
export CONNECTION_NAME

export GATEWAY_PIPELINE_NAME="${WHOAMI}_${NINE_CHAR_ID}_GW"
export INGESTION_PIPELINE_NAME="${WHOAMI}_${NINE_CHAR_ID}_IG"
export CLEANUP_JOB_NAME="${WHOAMI}_${NINE_CHAR_ID}_cleanup"
export TARGET_CATALOG="${TARGET_CATALOG:-main}"
export TARGET_SCHEMA="${WHOAMI}_${NINE_CHAR_ID}"
export STAGING_CATALOG="${TARGET_CATALOG}"
export STAGING_SCHEMA="${TARGET_SCHEMA}"
export ELOG_CATALOG="${ELOG_CATALOG:-main}"
export ELOG_SCHEMA="${ELOG_SCHEMA:-${WHOAMI}}"

# Build connection spec into STATE so we can export to tfvars
connection_spec_create

# Export connection options for Terraform (from STATE[conn_create_json])
CONN_JSON="${STATE[conn_create_json]}"
export TF_CONNECTION_NAME CONNECTION_TYPE TF_CONN_HOST TF_CONN_PORT TF_CONN_USER TF_CONN_PASSWORD
TF_CONNECTION_NAME=$(echo "$CONN_JSON" | jq -r '.name')
CONNECTION_TYPE=$(echo "$CONN_JSON" | jq -r '.connection_type')
TF_CONN_HOST=$(echo "$CONN_JSON" | jq -r '.options.host')
TF_CONN_PORT=$(echo "$CONN_JSON" | jq -r '.options.port')
TF_CONN_USER=$(echo "$CONN_JSON" | jq -r '.options.user')
TF_CONN_PASSWORD=$(echo "$CONN_JSON" | jq -r '.options.password')

# Ensure tf/ exists and has config
mkdir -p "$TF_DIR"
if [[ ! -f "${TF_DIR}/main.tf" ]]; then
  echo "Missing ${TF_DIR}/main.tf. Create deploy/tf/ with main.tf, variables.tf, and provider.tf (see deploy/tf/README)."
  return 1
fi

# Write terraform.tfvars from current env
cat > "$TFVARS_FILE" <<TFVARS
# Generated by 03_lakeflow_connect_demo_tf.sh - do not edit by hand

connection_name   = "$TF_CONNECTION_NAME"
connection_type   = "$CONNECTION_TYPE"
connection_host   = "$TF_CONN_HOST"
connection_port   = "$TF_CONN_PORT"
connection_user   = "$TF_CONN_USER"
connection_password = "$TF_CONN_PASSWORD"

gateway_pipeline_name    = "$GATEWAY_PIPELINE_NAME"
ingestion_pipeline_name  = "$INGESTION_PIPELINE_NAME"
cleanup_job_name         = "$CLEANUP_JOB_NAME"
target_catalog           = "$TARGET_CATALOG"
target_schema            = "$TARGET_SCHEMA"
staging_catalog          = "$STAGING_CATALOG"
staging_schema           = "$STAGING_SCHEMA"
elog_catalog             = "$ELOG_CATALOG"
elog_schema              = "$ELOG_SCHEMA"

gateway_continuous   = $([[ "$GATEWAY_PIPELINE_CONTINUOUS" == "true" ]] && echo "true" || echo "false")
ingestion_continuous = $([[ "$INGESTION_PIPELINE_CONTINUOUS" == "true" ]] && echo "true" || echo "false")
development_mode     = $PIPELINE_DEV_MODE
source_type          = "${SOURCE_TYPE:-SQLSERVER}"
db_catalog           = "$DB_CATALOG"
db_schema            = "$DB_SCHEMA"
cdc_ct_mode          = "$CDC_CT_MODE"
scd_type             = "${SCD_TYPE:-}"
ingestion_min_trigger = $INGESTION_PIPELINE_MIN_TRIGGER
jobs_performance_mode = "$JOBS_PERFORMANCE_MODE"
dbx_username         = "$DBX_USERNAME"

gateway_min_workers = ${GATEWAY_MIN_WORKERS:-0}
gateway_max_workers = ${GATEWAY_MAX_WORKERS:-0}
gateway_driver_node  = "${GATEWAY_DRIVER_NODE:-}"
gateway_worker_node  = "${GATEWAY_WORKER_NODE:-}"
TFVARS

# Optional: use Databricks provider from rsleedbx fork (num_workers_0 branch)
if [[ -n "${USE_NUM_WORKERS_0_PROVIDER:-}" ]] && [[ "${USE_NUM_WORKERS_0_PROVIDER}" != "0" ]]; then
  echo "Using Databricks provider from ${NUM_WORKERS_0_PROVIDER_REPO} branch ${NUM_WORKERS_0_PROVIDER_BRANCH}"
  BUILD_DIR="${TF_DIR}/.provider-build"
  mkdir -p "$BUILD_DIR"
  if [[ ! -d "${BUILD_DIR}/terraform-provider-databricks/.git" ]]; then
    git clone --depth 1 --branch "$NUM_WORKERS_0_PROVIDER_BRANCH" "$NUM_WORKERS_0_PROVIDER_REPO" "${BUILD_DIR}/terraform-provider-databricks" || return 1
  else
    (cd "${BUILD_DIR}/terraform-provider-databricks" && git fetch origin "$NUM_WORKERS_0_PROVIDER_BRANCH" && git checkout "$NUM_WORKERS_0_PROVIDER_BRANCH" && git pull) || return 1
  fi
  (cd "${BUILD_DIR}/terraform-provider-databricks" && go build -o terraform-provider-databricks .) || return 1
  # Terraform expects registry.terraform.io/databricks/databricks/<version>/<os>_<arch>/
  VERSION="0.0.0-num-workers-0"
  ARCH=$(uname -m)
  case "$ARCH" in
    x86_64) TF_ARCH="amd64" ;;
    arm64|aarch64) TF_ARCH="arm64" ;;
    *) TF_ARCH="$ARCH" ;;
  esac
  TF_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
  PLUGIN_PATH="${PLUGIN_DIR}/registry.terraform.io/databricks/databricks/${VERSION}/${TF_OS}_${TF_ARCH}"
  mkdir -p "$PLUGIN_PATH"
  cp "${BUILD_DIR}/terraform-provider-databricks/terraform-provider-databricks" "${PLUGIN_PATH}/terraform-provider-databricks_${VERSION}"
  export TF_PLUGIN_DIR="$PLUGIN_DIR"
  # Override required_providers version so Terraform uses the local binary
  if [[ -f "${TF_DIR}/versions.tf" ]]; then
    sed -i.bak 's/version = ">= 1.0.0"/version = "0.0.0-num-workers-0"/' "${TF_DIR}/versions.tf" 2>/dev/null || true
  fi
fi

# Run Terraform
echo -e "\nTerraform Lakeflow Connect demo"
echo -e "-------------------------------\n"
cd "$TF_DIR" || return 1
if [[ -n "${TF_PLUGIN_DIR:-}" ]]; then
  terraform init -plugin-dir="$TF_PLUGIN_DIR" -upgrade || return 1
else
  terraform init -upgrade || return 1
fi
terraform plan -out=tfplan -var-file=terraform.tfvars "$@" || return 1
echo -e "\nApply with: cd deploy/tf && terraform apply tfplan"
echo -e "Or apply now: terraform apply -var-file=terraform.tfvars"
# Uncomment to apply automatically:
# terraform apply -var-file=terraform.tfvars -auto-approve "$@" || return 1

# #############################################################################
# Click on UI (same as 03_lakeflow_connect_demo.sh)
# #############################################################################
echo -e "\nClick on UI"
echo -e   "-----------\n"

echo -e "elog/GW Tlmy  : ${DATABRICKS_HOST_NAME}/explore/data/${ELOG_CATALOG}/${ELOG_SCHEMA}"
echo -e "Staging schema: ${DATABRICKS_HOST_NAME}/explore/data/${STAGING_CATALOG}/${STAGING_SCHEMA}"
echo -e "Target schema : ${DATABRICKS_HOST_NAME}/explore/data/${TARGET_CATALOG}/${TARGET_SCHEMA}"
echo -e "Connection    : ${DATABRICKS_HOST_NAME}/explore/connections/${CONNECTION_NAME}"

INGESTION_JOB_ID=$(terraform output -raw ingestion_job_id 2>/dev/null)
if [[ -n "$INGESTION_JOB_ID" ]]; then
  echo -e "Job           : ${DATABRICKS_HOST_NAME}/jobs/${INGESTION_JOB_ID} \n"
else
  echo -e "Job           : (after apply: cd deploy/tf && terraform output ingestion_job_id) \n"
fi

DB_EXIT_ON_ERROR="PRINT_EXIT" DBX pipelines list-pipelines --filter "name like '${WHOAMI}_%'"
jq --arg url "$DATABRICKS_HOST_NAME" -r 'sort_by(.name) | .[] | [ .name, .pipeline_id, .state, ($url + "/pipelines/" + .pipeline_id) ] | @tsv' /tmp/dbx_stdout.$$ 2>/dev/null || true
