DECLARE
  table_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(table_exists, -955);
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE intpk (
      pk NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      dt TIMESTAMP
    )
  ';
EXCEPTION
  WHEN table_exists THEN
    NULL; -- Table already exists, so do nothing.
END;


    CREATE TABLE intpk (
      pk NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      dt TIMESTAMP
    );
	CREATE INDEX idx_intpk_dt ON intpk (dt);   
    
   CREATE TABLE dtix (
      dt TIMESTAMP
    );
	CREATE INDEX idx_dtix_dt ON dtix (dt);   
    
    SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') FROM DUAL;

BEGIN
    FOR i IN 1 .. 1000 LOOP
        INSERT INTO intpk (dt) VALUES (CURRENT_TIMESTAMP);
    END LOOP;
    COMMIT; -- Commit the changes after the loop
END;

BEGIN
    FOR i IN 1 .. 1000 LOOP
        INSERT INTO dtix (dt) VALUES (CURRENT_TIMESTAMP);
    END LOOP;
    COMMIT; -- Commit the changes after the loop
END;
